// Learning content: words, travel phrases and phrases of the day in German, English, Nepali and Korean.
// Word rows: [id, topic, level(b|i|a), de, en, ne, romanised ne, example de, example en, example ne, note?]
// Edit here, then run `npm run audio` (or the "Generate audio" workflow) to refresh native audio.
export const RAW = [
["g1","greet","b","Hallo","Hello","नमस्ते","namaste","Hallo, wie geht's?","Hello, how are you?","नमस्ते, तपाईंलाई कस्तो छ?"],
["g2","greet","b","Danke","Thank you","धन्यवाद","dhanyabād","Danke für das Essen.","Thank you for the food.","खानाको लागि धन्यवाद।"],
["g3","greet","b","Bitte","Please","कृपया","kripayā","Bitte setzen Sie sich.","Please sit down.","कृपया बस्नुहोस्।"],
["g4","greet","b","Ja","Yes","हो","ho","Ja, gern.","Yes, gladly.","हो, खुसीसाथ।"],
["g5","greet","b","Nein","No","होइन","hoina","Nein, danke.","No, thank you.","होइन, धन्यवाद।"],
["g6","greet","b","Entschuldigung","Excuse me","माफ गर्नुहोस्","māph garnuhos","Entschuldigung, wo ist der Bahnhof?","Excuse me, where is the station?","माफ गर्नुहोस्, स्टेसन कहाँ छ?"],
["g7","greet","b","Auf Wiedersehen","Goodbye","फेरि भेटौँला","pheri bheṭauṁlā","Auf Wiedersehen und bis bald!","Goodbye and see you soon!","फेरि भेटौँला, चाँडै भेटौँ!"],
["g8","greet","b","Guten Morgen","Good morning","शुभ प्रभात","shubha prabhāt","Guten Morgen, Frau Weber.","Good morning, Mrs Weber.","शुभ प्रभात, वेबर जी।"],
["n1","numbers","b","eins","one","एक","ek","Ein Tee, bitte.","One tea, please.","एक कप चिया, कृपया।"],
["n2","numbers","b","zwei","two","दुई","dui","Zwei Kaffee, bitte.","Two coffees, please.","दुई कप कफी, कृपया।"],
["n3","numbers","b","drei","three","तीन","tin","Ich habe drei Kinder.","I have three children.","मेरा तीन जना बच्चा छन्।"],
["n4","numbers","b","vier","four","चार","chār","Es ist vier Uhr.","It is four o'clock.","चार बज्यो।"],
["n5","numbers","b","fünf","five","पाँच","pā̃ch","Fünf Minuten, bitte.","Five minutes, please.","पाँच मिनेट, कृपया।"],
["n6","numbers","b","zehn","ten","दश","das","Das kostet zehn Euro.","That costs ten euros.","यसको मूल्य दश युरो हो।"],
["f1","family","b","die Mutter","mother","आमा","āmā","Meine Mutter kocht gern.","My mother likes to cook.","मेरी आमालाई खाना पकाउन मन पर्छ।"],
["f2","family","b","der Vater","father","बुबा","bubā","Mein Vater arbeitet in Kathmandu.","My father works in Kathmandu.","मेरो बुबा काठमाडौँमा काम गर्नुहुन्छ।"],
["f3","family","b","der Bruder","brother","दाजु","dāju","Mein Bruder ist älter als ich.","My brother is older than me.","मेरो दाजु मभन्दा जेठो हुनुहुन्छ।",{en:"Nepali uses two words: दाजु (dāju) for an elder brother and भाइ (bhāi) for a younger brother.",de:"Nepali hat zwei Wörter: दाजु (dāju) für den älteren und भाइ (bhāi) für den jüngeren Bruder.",ne:"दाजु = जेठो, भाइ = कान्छो।"}],
["f4","family","b","die Schwester","sister","दिदी","didi","Meine Schwester studiert.","My sister is studying.","मेरी दिदी पढ्दै हुनुहुन्छ।",{en:"Nepali uses दिदी (didi) for an elder sister and बहिनी (bahini) for a younger sister.",de:"Nepali: दिदी (didi) = ältere, बहिनी (bahini) = jüngere Schwester.",ne:"दिदी = जेठी, बहिनी = कान्छी।"}],
["f5","family","b","die Familie","family","परिवार","parivār","Meine Familie ist groß.","My family is big.","मेरो परिवार ठूलो छ।"],
["f6","family","b","das Kind","child","बच्चा","bachchā","Das Kind spielt.","The child is playing.","बच्चा खेल्दैछ।"],
["d1","food","b","das Wasser","water","पानी","pāni","Ein Glas Wasser, bitte.","A glass of water, please.","एक गिलास पानी, कृपया।"],
["d2","food","b","der Reis","rice","भात","bhāt","Wir essen Reis mit Linsen.","We eat rice with lentils.","हामी दाल भात खान्छौँ।",{en:"भात is cooked rice; uncooked rice is चामल (chāmal).",de:"भात ist gekochter Reis; roher Reis heißt चामल (chāmal).",ne:"पकाएको = भात, नपकाएको = चामल।"}],
["d3","food","b","das Brot","bread","रोटी","roṭi","Das Brot ist frisch.","The bread is fresh.","रोटी ताजा छ।"],
["d4","food","b","der Tee","tea","चिया","chiyā","Möchtest du Tee?","Would you like tea?","चिया खानुहुन्छ?",{en:"In Nepali you 'eat' tea: चिया खानु (chiyā khānu).",de:"Auf Nepali „isst“ man Tee: चिया खानु (chiyā khānu).",ne:"चिया खानु भनिन्छ।"}],
["d5","food","b","die Milch","milk","दूध","dudh","Kaffee mit Milch, bitte.","Coffee with milk, please.","दूध हालेको कफी, कृपया।"],
["d6","food","b","das Essen","food","खाना","khānā","Das Essen ist lecker.","The food is tasty.","खाना मीठो छ।"],
["h1","home","b","das Haus","house","घर","ghar","Unser Haus ist klein.","Our house is small.","हाम्रो घर सानो छ।"],
["h2","home","b","das Buch","book","किताब","kitāb","Ich lese ein Buch.","I am reading a book.","म किताब पढ्दैछु।"],
["h3","home","b","die Tür","door","ढोका","ḍhokā","Bitte mach die Tür zu.","Please close the door.","कृपया ढोका बन्द गर।"],
["v1","verbs","b","essen","to eat","खानु","khānu","Wir essen um sieben.","We eat at seven.","हामी सात बजे खान्छौँ।"],
["v2","verbs","b","trinken","to drink","पिउनु","piunu","Ich trinke viel Wasser.","I drink a lot of water.","म धेरै पानी पिउँछु।"],
["v3","verbs","b","gehen","to go","जानु","jānu","Ich gehe nach Hause.","I am going home.","म घर जाँदैछु।"],
["v4","verbs","b","kommen","to come","आउनु","āunu","Woher kommst du?","Where do you come from?","तिमी कहाँबाट आएको?"],
["v5","verbs","b","sprechen","to speak","बोल्नु","bolnu","Sprechen Sie Englisch?","Do you speak English?","तपाईं अंग्रेजी बोल्नुहुन्छ?"],
["v6","verbs","b","verstehen","to understand","बुझ्नु","bujhnu","Ich verstehe nicht.","I don't understand.","मैले बुझिनँ।"],
["t1","time","b","heute","today","आज","āja","Heute ist es warm.","It is warm today.","आज गर्मी छ।"],
["t2","time","b","morgen","tomorrow","भोलि","bholi","Bis morgen!","See you tomorrow!","भोलि भेटौँला!"],
["t3","time","b","gestern","yesterday","हिजो","hijo","Gestern war ich müde.","Yesterday I was tired.","हिजो म थाकेको थिएँ।"],
["r1","directions","b","links","left","बायाँ","bāyā̃","Gehen Sie nach links.","Go left.","बायाँतिर जानुहोस्।"],
["r2","directions","b","rechts","right","दायाँ","dāyā̃","Das Hotel ist rechts.","The hotel is on the right.","होटल दायाँतिर छ।"],
["r3","directions","b","geradeaus","straight ahead","सिधा","sidhā","Immer geradeaus.","Keep going straight ahead.","सिधा जानुहोस्।"],
["s1","shopping","b","teuer","expensive","महँगो","mahãgo","Das ist zu teuer.","That is too expensive.","यो धेरै महँगो भयो।"],
["s2","shopping","b","billig","cheap","सस्तो","sasto","Das Hemd ist billig.","The shirt is cheap.","सर्ट सस्तो छ।"],
["s3","shopping","b","Wie viel?","How much?","कति?","kati?","Wie viel kostet das?","How much does this cost?","यसको कति हो?"],
["w1","work","i","die Arbeit","work","काम","kām","Ich habe heute viel Arbeit.","I have a lot of work today.","आज मसँग धेरै काम छ।"],
["w2","work","i","der Kollege","colleague","सहकर्मी","sahakarmi","Mein Kollege hilft mir.","My colleague helps me.","मेरो सहकर्मीले मलाई मद्दत गर्छन्।"],
["w3","work","i","die Besprechung","meeting","बैठक","baiṭhak","Die Besprechung beginnt um zehn.","The meeting starts at ten.","बैठक दश बजे सुरु हुन्छ।"],
["w4","work","i","die Nachricht","message","सन्देश","sandesh","Ich schicke dir eine Nachricht.","I'll send you a message.","म तिमीलाई सन्देश पठाउँछु।"],
["w5","work","i","die Rechnung","bill","बिल","bil","Die Rechnung, bitte.","The bill, please.","बिल दिनुहोस्।"],
["w6","work","i","pünktlich","on time","समयमै","samayamai","Bitte sei pünktlich.","Please be on time.","कृपया समयमै आउनू।"],
["w7","work","i","die Erfahrung","experience","अनुभव","anubhav","Sie hat viel Erfahrung.","She has a lot of experience.","उहाँसँग धेरै अनुभव छ।"],
["w8","work","i","die Gelegenheit","opportunity","अवसर","avasar","Das ist eine gute Gelegenheit.","That is a good opportunity.","यो राम्रो अवसर हो।"],
["w9","work","i","sich erinnern","to remember","सम्झनु","samjhanu","Ich erinnere mich an dich.","I remember you.","म तिमीलाई सम्झन्छु।"],
["a1","abstract","a","die Verantwortung","responsibility","जिम्मेवारी","jimmevāri","Er übernimmt die Verantwortung.","He takes responsibility.","उहाँ जिम्मेवारी लिनुहुन्छ।"],
["a2","abstract","a","die Herausforderung","challenge","चुनौती","chunauti","Das ist eine große Herausforderung.","That is a big challenge.","यो ठूलो चुनौती हो।"],
["a3","abstract","a","die Voraussetzung","prerequisite","पूर्वशर्त","pūrvashart","Deutschkenntnisse sind eine Voraussetzung.","Knowledge of German is a prerequisite.","जर्मन भाषाको ज्ञान पूर्वशर्त हो।"],
["a4","abstract","a","die Vereinbarung","agreement","सम्झौता","samjhautā","Wir haben eine Vereinbarung getroffen.","We reached an agreement.","हामीले सम्झौता गर्यौँ।"],
["a5","abstract","a","die Entwicklung","development","विकास","vikās","Die Entwicklung dauert zwei Jahre.","The development takes two years.","विकासमा दुई वर्ष लाग्छ।"],
["a6","abstract","a","die Nachhaltigkeit","sustainability","दिगोपन","digopan","Nachhaltigkeit ist uns wichtig.","Sustainability is important to us.","दिगोपन हाम्रो लागि महत्त्वपूर्ण छ।"]
];

// Phrase of the day (advanced): [id, de, en, ne, romanised ne, usage note]
export const PHR = [
["p1","Ich drücke dir die Daumen.","I'll keep my fingers crossed for you.","तिम्रो लागि शुभकामना!","timro lāgi shubhakāmanā!",{en:"Wishing someone luck before an exam or interview.",de:"Jemandem vor einer Prüfung oder einem Gespräch Glück wünschen.",ne:"परीक्षा वा अन्तर्वार्ताअघि शुभकामना दिँदा।"}],
["p2","Alles in Butter.","Everything's fine.","सबै ठीक छ।","sabai ṭhik cha.",{en:"Casual. Reassures someone that things are going well.",de:"Umgangssprachlich: Alles läuft gut.",ne:"अनौपचारिक: सबै राम्रो चलिरहेको छ।"}],
["p3","Ich verstehe nur Bahnhof.","It's all Greek to me.","मैले केही बुझिनँ।","maile kehi bujhinã.",{en:"Informal. You don't understand anything that was said.",de:"Informell: Man versteht gar nichts.",ne:"अनौपचारिक: केही पनि नबुझ्दा।"}],
["p4","Das ist nicht mein Bier.","That's not my business.","त्यो मेरो काम होइन।","tyo mero kām hoina.",{en:"Informal. Something is not your responsibility.",de:"Informell: Dafür bin ich nicht zuständig.",ne:"अनौपचारिक: त्यो आफ्नो जिम्मा होइन।"}],
["p5","Auf jeden Fall.","Definitely.","पक्कै पनि।","pakkai pani.",{en:"Strong agreement. Works in formal and casual speech.",de:"Starke Zustimmung, formell und informell.",ne:"पूर्ण सहमति जनाउन।"}]
];

// Travel phrases: [id, situation, de, en, ne, romanised ne]
export const TRV = [
["x1","airport","Wo ist der Check-in-Schalter?","Where is the check-in counter?","चेक-इन काउन्टर कहाँ छ?","chek-in kāunṭar kahā̃ cha?"],
["x2","airport","Mein Koffer ist nicht angekommen.","My suitcase did not arrive.","मेरो सुटकेस आइपुगेन।","mero suṭkes āipugena."],
["x3","immigration","Ich bin als Tourist hier.","I am here as a tourist.","म पर्यटकको रूपमा आएको हुँ।","ma paryaṭakko rūpmā āeko hũ."],
["x4","hotel","Ich habe eine Reservierung.","I have a reservation.","मेरो बुकिङ छ।","mero bukiṅ cha."],
["x5","hotel","Wann gibt es Frühstück?","When is breakfast?","बिहानको खाजा कति बजे हो?","bihānako khājā kati baje ho?"],
["x6","restaurant","Die Speisekarte, bitte.","The menu, please.","मेनु दिनुहोस्।","menu dinuhos."],
["x7","restaurant","Ich bin Vegetarier.","I am vegetarian.","म शाकाहारी हुँ।","ma shākāhāri hũ."],
["x8","restaurant","Nicht zu scharf, bitte.","Not too spicy, please.","धेरै पिरो नबनाउनुहोस्।","dherai piro nabanāunuhos."],
["x9","transport","Wann fährt der nächste Bus?","When does the next bus leave?","अर्को बस कति बजे छुट्छ?","arko bas kati baje chuṭcha?"],
["x10","transport","Bitte bringen Sie mich zu dieser Adresse.","Please take me to this address.","मलाई यो ठेगानामा लैजानुहोस्।","malāi yo ṭhegānāmā laijānuhos."],
["x11","transport","Eine Fahrkarte nach Pokhara, bitte.","One ticket to Pokhara, please.","पोखराको एउटा टिकट दिनुहोस्।","pokharāko euṭā ṭikaṭ dinuhos."],
["x12","directions","Wo ist die Toilette?","Where is the toilet?","शौचालय कहाँ छ?","shauchālaya kahā̃ cha?"],
["x13","directions","Ist es weit von hier?","Is it far from here?","यहाँबाट टाढा छ?","yahā̃bāṭa ṭāḍhā cha?"],
["x14","money","Kann ich mit Karte zahlen?","Can I pay by card?","कार्डबाट तिर्न सकिन्छ?","kārḍbāṭa tirna sakincha?"],
["x15","money","Geht es etwas günstiger?","Can you make it a bit cheaper?","अलि घटाउन मिल्छ?","ali ghaṭāuna milcha?"],
["x16","emergency","Hilfe!","Help!","बचाउ!","bachāu!"],
["x17","emergency","Rufen Sie einen Krankenwagen!","Call an ambulance!","एम्बुलेन्स बोलाउनुहोस्!","embulens bolāunuhos!"],
["x18","emergency","Ich brauche einen Arzt.","I need a doctor.","मलाई डाक्टर चाहियो।","malāi ḍākṭar chāhiyo."],
["x19","emergency","Ich habe meinen Pass verloren.","I have lost my passport.","मेरो राहदानी हरायो।","mero rāhadāni harāyo."],
["x20","phone","Gibt es hier WLAN?","Is there Wi-Fi here?","यहाँ वाइफाइ छ?","yahā̃ wāiphāi cha?"],
["x21","social","Ich heiße Anna.","My name is Anna.","मेरो नाम अन्ना हो।","mero nām annā ho."],
["x22","social","Freut mich!","Nice to meet you!","तपाईंलाई भेटेर खुसी लाग्यो!","tapāī̃lāi bheṭera khusi lāgyo!"]
];

// Korean: id → [Hangul, romanisation (Revised Romanization), example sentence, note?]
// Examples match the English example of the same item.
export const KO = {
  g1:["안녕하세요","annyeonghaseyo","안녕하세요, 어떻게 지내세요?"],
  g2:["감사합니다","gamsahamnida","음식 감사합니다."],
  g3:["부탁합니다","butakamnida","여기 앉으세요."],
  g4:["네","ne","네, 좋아요."],
  g5:["아니요","aniyo","아니요, 괜찮아요."],
  g6:["실례합니다","sillyehamnida","실례합니다, 역이 어디예요?"],
  g7:["안녕히 가세요","annyeonghi gaseyo","안녕히 가세요, 또 만나요!"],
  g8:["좋은 아침입니다","joeun achimimnida","좋은 아침입니다, 베버 씨."],
  n1:["하나","hana","차 한 잔 주세요."],
  n2:["둘","dul","커피 두 잔 주세요."],
  n3:["셋","set","저는 아이가 세 명 있어요."],
  n4:["넷","net","네 시예요."],
  n5:["다섯","daseot","오 분만 기다려 주세요."],
  n6:["열","yeol","이건 십 유로예요.",{en:"Korean has two number systems: native numbers (하나, 둘, 셋 …) for counting things and hours, Sino-Korean (일, 이, 삼 … 십) for money, minutes and dates.",de:"Koreanisch hat zwei Zahlensysteme: koreanische Zahlen (하나, 둘, 셋 …) zum Zählen und für Stunden, sino-koreanische (일, 이, 삼 … 십) für Geld, Minuten und Daten.",ne:"कोरियालीमा दुई अङ्क प्रणाली छन्: गन्न र घण्टाका लागि 하나, 둘, 셋 …; पैसा, मिनेट र मितिका लागि 일, 이, 삼 … 십।",ko:"고유어 수(하나, 둘, 셋…)는 개수·시간에, 한자어 수(일, 이, 삼…십)는 돈·분·날짜에 씁니다."}],
  f1:["어머니","eomeoni","어머니는 요리를 좋아하세요."],
  f2:["아버지","abeoji","아버지는 카트만두에서 일하세요."],
  f3:["형","hyeong","형은 저보다 나이가 많아요.",{en:"The word depends on who is speaking: 형 (hyeong) is a man's older brother, 오빠 (oppa) a woman's older brother, 남동생 (namdongsaeng) a younger brother.",de:"Das Wort hängt vom Sprecher ab: 형 (hyeong) älterer Bruder eines Mannes, 오빠 (oppa) einer Frau, 남동생 (namdongsaeng) jüngerer Bruder.",ne:"बोल्ने व्यक्तिअनुसार: 형 = पुरुषको दाजु, 오빠 = महिलाको दाजु, 남동생 = भाइ।",ko:"형: 남자가 부르는 형, 오빠: 여자가 부르는 오빠, 남동생: 동생."}],
  f4:["누나","nuna","누나는 공부하고 있어요.",{en:"누나 (nuna) is a man's older sister, 언니 (eonni) a woman's older sister, 여동생 (yeodongsaeng) a younger sister.",de:"누나 (nuna) ältere Schwester eines Mannes, 언니 (eonni) einer Frau, 여동생 (yeodongsaeng) jüngere Schwester.",ne:"누나 = पुरुषको दिदी, 언니 = महिलाको दिदी, 여동생 = बहिनी।",ko:"누나: 남자가 부르는 누나, 언니: 여자가 부르는 언니, 여동생: 동생."}],
  f5:["가족","gajok","우리 가족은 대가족이에요."],
  f6:["아이","ai","아이가 놀고 있어요."],
  d1:["물","mul","물 한 잔 주세요."],
  d2:["밥","bap","우리는 밥과 렌틸콩을 먹어요.",{en:"밥 (bap) is cooked rice and also means 'meal'; uncooked rice is 쌀 (ssal).",de:"밥 (bap) ist gekochter Reis und heißt auch „Mahlzeit“; roher Reis ist 쌀 (ssal).",ne:"밥 = पकाएको भात (खाना पनि), 쌀 = चामल।",ko:"밥은 지은 밥(식사), 쌀은 익히지 않은 쌀입니다."}],
  d3:["빵","ppang","빵이 신선해요."],
  d4:["차","cha","차 드실래요?"],
  d5:["우유","uyu","우유 넣은 커피 주세요."],
  d6:["음식","eumsik","음식이 맛있어요."],
  h1:["집","jip","우리 집은 작아요."],
  h2:["책","chaek","저는 책을 읽고 있어요."],
  h3:["문","mun","문 좀 닫아 주세요."],
  v1:["먹다","meokda","우리는 일곱 시에 먹어요."],
  v2:["마시다","masida","저는 물을 많이 마셔요."],
  v3:["가다","gada","저는 집에 가요."],
  v4:["오다","oda","어디에서 왔어요?"],
  v5:["말하다","malhada","영어 할 줄 아세요?"],
  v6:["이해하다","ihaehada","이해가 안 돼요."],
  t1:["오늘","oneul","오늘은 따뜻해요."],
  t2:["내일","naeil","내일 봐요!"],
  t3:["어제","eoje","어제는 피곤했어요."],
  r1:["왼쪽","oenjjok","왼쪽으로 가세요."],
  r2:["오른쪽","oreunjjok","호텔은 오른쪽에 있어요."],
  r3:["똑바로","ttokbaro","계속 똑바로 가세요."],
  s1:["비싸다","bissada","너무 비싸요."],
  s2:["싸다","ssada","그 셔츠는 싸요."],
  s3:["얼마예요?","eolmayeyo?","이거 얼마예요?"],
  w1:["일","il","오늘 일이 많아요."],
  w2:["동료","dongnyo","제 동료가 저를 도와줘요."],
  w3:["회의","hoeui","회의는 열 시에 시작해요."],
  w4:["메시지","mesiji","메시지 보낼게요."],
  w5:["계산서","gyesanseo","계산서 주세요."],
  w6:["제시간에","jesigane","제시간에 와 주세요."],
  w7:["경험","gyeongheom","그녀는 경험이 많아요."],
  w8:["기회","gihoe","좋은 기회예요."],
  w9:["기억하다","gieokada","저는 당신을 기억해요."],
  a1:["책임","chaegim","그는 책임을 져요."],
  a2:["도전","dojeon","그건 큰 도전이에요."],
  a3:["전제 조건","jeonje jogeon","독일어 실력은 전제 조건이에요."],
  a4:["합의","habui","우리는 합의에 도달했어요."],
  a5:["개발","gaebal","개발은 이 년 걸려요."],
  a6:["지속 가능성","jisok ganeungseong","지속 가능성은 우리에게 중요해요."],
  p1:["행운을 빌어요!","haenguneul bireoyo!"],
  p2:["다 잘 되고 있어요.","da jal doego isseoyo."],
  p3:["하나도 모르겠어요.","hanado moreugesseoyo."],
  p4:["그건 제 일이 아니에요.","geugeon je iri anieyo."],
  p5:["물론이죠.","mullonijyo."],
  x1:["체크인 카운터가 어디예요?","chekeuin kaunteoga eodiyeyo?"],
  x2:["제 여행 가방이 안 왔어요.","je yeohaeng gabangi an wasseoyo."],
  x3:["관광하러 왔어요.","gwangwanghareo wasseoyo."],
  x4:["예약했어요.","yeyakaesseoyo."],
  x5:["아침 식사는 몇 시예요?","achim siksaneun myeot siyeyo?"],
  x6:["메뉴판 주세요.","menyupan juseyo."],
  x7:["저는 채식주의자예요.","jeoneun chaesikjuuijayeyo."],
  x8:["너무 맵지 않게 해 주세요.","neomu maepji anke hae juseyo."],
  x9:["다음 버스는 언제 출발해요?","daeum beoseuneun eonje chulbalhaeyo?"],
  x10:["이 주소로 가 주세요.","i jusoro ga juseyo."],
  x11:["포카라행 표 한 장 주세요.","pokarahaeng pyo han jang juseyo."],
  x12:["화장실이 어디예요?","hwajangsiri eodiyeyo?"],
  x13:["여기서 멀어요?","yeogiseo meoreoyo?"],
  x14:["카드로 계산할 수 있어요?","kadeuro gyesanhal su isseoyo?"],
  x15:["좀 깎아 주실 수 있어요?","jom kkakka jusil su isseoyo?"],
  x16:["도와주세요!","dowajuseyo!"],
  x17:["구급차를 불러 주세요!","gugeupchareul bulleo juseyo!"],
  x18:["의사가 필요해요.","uisaga piryohaeyo."],
  x19:["여권을 잃어버렸어요.","yeogwoneul ireobeoryeosseoyo."],
  x20:["여기 와이파이 있어요?","yeogi waipai isseoyo?"],
  x21:["제 이름은 안나예요.","je ireumeun annayeyo."],
  x22:["만나서 반갑습니다!","mannaseo bangapseumnida!"],
};

// Romanisation per language: rom.ne (Nepali) and rom.ko (Korean). Notes are per target language (notes.ne, notes.ko);
// phrase usage notes (kind "phrase") apply to every language.
const base = RAW.map(r=>({id:r[0],topic:r[1],level:r[2],de:r[3],en:r[4],ne:r[5],rom:{ne:r[6]},ex:{de:r[7],en:r[8],ne:r[9]},notes:r[10]?{ne:r[10]}:{},note:null,kind:"word"}))
  .concat(TRV.map(r=>({id:r[0],topic:"travel",sit:r[1],level:"b",de:r[2],en:r[3],ne:r[4],rom:{ne:r[5]},ex:null,notes:{},note:null,kind:"travel"})))
  .concat(PHR.map(r=>({id:r[0],topic:"phrase",level:"a",de:r[1],en:r[2],ne:r[3],rom:{ne:r[4]},ex:null,notes:{},note:r[5],kind:"phrase"})));
for (const it of base) {
  const k = KO[it.id];
  if (!k) continue;
  it.ko = k[0]; it.rom.ko = k[1];
  if (it.ex && k[2]) it.ex.ko = k[2];
  if (k[3]) it.notes.ko = k[3];
}
export const ITEMS = base;
export const BY = Object.fromEntries(ITEMS.map(i=>[i.id,i]));
export const WORDS = ITEMS.filter(i=>i.kind==="word");
